#!/usr/bin/env bash
#displays the time for 12 hours and 59 minutes
MINUTES=0
HOURS=0
while [ $HOURS -lt 13 ]
do
	echo "Hour: $HOURS"
	MINUTES=1
	while [ $MINUTES -lt 60 ]
	do
		echo $MINUTES
		((MINUTES++))
	done
	((HOURS++))
done
